// Command apiinventory generates the reviewed Genesis v1 exported API surface.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/token"
	"go/types"
	"os"
	"sort"
	"strconv"
	"strings"
	"unicode"

	"golang.org/x/tools/go/packages"
)

const headerPrefix = `# Genesis v1 exported API inventory

This file is generated by ` + "`go run ./internal/cmd/apiinventory`" + `. It inventories exported constants, variables, types, functions, and methods that form the v1 review surface. Packages under ` + "`examples`" + ` and ` + "`internal`" + ` are excluded`

func main() {
	writePath := flag.String("write", "", "write the generated inventory to this path")
	checkPath := flag.String("check", "", "fail if this path differs from the generated inventory")
	moduleDir := flag.String("dir", ".", "module directory to inventory")
	compatBaseline := flag.String("compat-baseline", "", "fail on removals or signature changes relative to this inventory")
	allowBreaking := flag.String("allow-breaking", "", "inventory subset containing reviewed compatibility exceptions")
	expectBreaking := flag.String("expect-breaking", "", "inventory subset containing the approved replacement signatures")
	allowRemovals := flag.String("allow-removals", "", "inventory subset containing reviewed API removals with no replacement")
	legacyPublicExamples := flag.Bool("legacy-public-examples", false, "allow importable example packages only while rebuilding a frozen legacy baseline")
	flag.Parse()
	if *writePath != "" && *checkPath != "" {
		fatalf("-write and -check are mutually exclusive")
	}
	if *compatBaseline == "" && (*allowBreaking != "" || *expectBreaking != "" || *allowRemovals != "") {
		fatalf("compatibility exception files require -compat-baseline")
	}
	if *legacyPublicExamples && (*moduleDir == "." || *checkPath == "") {
		fatalf("-legacy-public-examples requires a non-default -dir and -check for frozen baseline reconstruction")
	}

	generated, err := generate(*moduleDir, *legacyPublicExamples)
	if err != nil {
		fatalf("generate inventory: %v", err)
	}
	switch {
	case *writePath != "":
		if err := os.WriteFile(*writePath, generated, 0o644); err != nil {
			fatalf("write inventory: %v", err)
		}
	case *checkPath != "":
		current, err := os.ReadFile(*checkPath)
		if err != nil {
			fatalf("read inventory: %v", err)
		}
		if !bytes.Equal(current, generated) {
			fatalf("%s is stale; run make api-inventory", *checkPath)
		}
	default:
		if *compatBaseline == "" {
			_, _ = os.Stdout.Write(generated)
		}
	}
	if *compatBaseline != "" {
		if err := checkCompatibility(generated, *compatBaseline, *allowBreaking, *expectBreaking, *allowRemovals); err != nil {
			fatalf("compatibility check: %v", err)
		}
	}
}

func generate(moduleDir string, legacyPublicExamples bool) ([]byte, error) {
	cfg := &packages.Config{
		Dir:  moduleDir,
		Mode: packages.NeedName | packages.NeedTypes | packages.NeedModule,
	}
	loaded, err := packages.Load(cfg, "./...")
	if err != nil {
		return nil, err
	}
	if packages.PrintErrors(loaded) > 0 {
		return nil, fmt.Errorf("package loading failed")
	}

	pkgs := make([]*packages.Package, 0, len(loaded))
	for _, pkg := range loaded {
		if pkg.Module == nil || pkg.PkgPath == "" {
			continue
		}
		rel := strings.TrimPrefix(pkg.PkgPath, pkg.Module.Path)
		isExample := strings.HasPrefix(rel, "/examples/") || rel == "/examples"
		isInternal := strings.Contains(rel, "/internal/") || strings.HasSuffix(rel, "/internal")
		if isExample && pkg.Name != "main" && !isInternal && !legacyPublicExamples {
			return nil, fmt.Errorf("importable example package must move under internal: %s", pkg.PkgPath)
		}
		if pkg.Name == "main" || isExample || strings.HasPrefix(rel, "/internal/") || rel == "/internal" {
			continue
		}
		pkgs = append(pkgs, pkg)
	}
	sort.Slice(pkgs, func(i, j int) bool { return pkgs[i].PkgPath < pkgs[j].PkgPath })

	var out bytes.Buffer
	out.WriteString(inventoryHeader(pkgs))
	for _, pkg := range pkgs {
		rel := strings.TrimPrefix(pkg.PkgPath, pkg.Module.Path+"/")
		fmt.Fprintf(&out, "## `%s`\n\n", rel)
		for _, entry := range packageEntries(pkg.Types) {
			fmt.Fprintf(&out, "- %s\n", entry)
		}
		out.WriteByte('\n')
	}
	return append(bytes.TrimRight(out.Bytes(), "\n"), '\n'), nil
}

func inventoryHeader(pkgs []*packages.Package) string {
	header := headerPrefix
	for _, pkg := range pkgs {
		if strings.TrimPrefix(pkg.PkgPath, pkg.Module.Path+"/") == "testkit" {
			return header + "; `testkit` is included because it is an importable module package.\n\n"
		}
	}
	return header + ".\n\n"
}

func packageEntries(pkg *types.Package) []string {
	printer := apiPrinter{pkg: pkg}
	entries := make([]string, 0)
	scope := pkg.Scope()
	for _, name := range scope.Names() {
		if !token.IsExported(name) {
			continue
		}
		obj := scope.Lookup(name)
		switch value := obj.(type) {
		case *types.Const:
			entries = append(entries, "const: `const "+value.Name()+" "+printer.typeString(value.Type())+" = "+value.Val().ExactString()+"`")
		case *types.Var:
			entries = append(entries, "var: `var "+value.Name()+" "+printer.typeString(value.Type())+"`")
		case *types.Func:
			entries = append(entries, "func: `func "+value.Name()+printer.signature(value.Signature())+"`")
		case *types.TypeName:
			entries = append(entries, "type: `"+printer.typeDeclaration(value)+"`")
			entries = append(entries, printer.exportedMethods(value)...)
		}
	}
	sort.Strings(entries)
	return entries
}

type apiPrinter struct {
	pkg *types.Package
}

func (p apiPrinter) typeDeclaration(obj *types.TypeName) string {
	if obj.IsAlias() {
		alias, ok := obj.Type().(*types.Alias)
		if !ok {
			return "type " + obj.Name() + " = " + p.typeString(types.Unalias(obj.Type()))
		}
		return "type " + obj.Name() + p.typeParameters(alias.TypeParams()) + " = " + p.typeString(alias.Rhs())
	}

	named, ok := obj.Type().(*types.Named)
	if !ok {
		return "type " + obj.Name() + " " + p.typeString(obj.Type())
	}
	return "type " + obj.Name() + p.typeParameters(named.TypeParams()) + " " + p.typeString(named.Underlying())
}

func (p apiPrinter) typeParameters(params *types.TypeParamList) string {
	if params == nil || params.Len() == 0 {
		return ""
	}
	parts := make([]string, params.Len())
	for i := range params.Len() {
		param := params.At(i)
		parts[i] = param.Obj().Name() + " " + p.typeString(param.Constraint())
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

func (p apiPrinter) typeString(typ types.Type) string {
	switch typ := typ.(type) {
	case *types.Basic:
		return typ.Name()
	case *types.Array:
		return fmt.Sprintf("[%d]%s", typ.Len(), p.typeString(typ.Elem()))
	case *types.Slice:
		return "[]" + p.typeString(typ.Elem())
	case *types.Struct:
		return p.structType(typ)
	case *types.Pointer:
		return "*" + p.typeString(typ.Elem())
	case *types.Tuple:
		return p.tuple(typ, false)
	case *types.Signature:
		return "func" + p.signature(typ)
	case *types.Interface:
		return p.interfaceType(typ)
	case *types.Map:
		return "map[" + p.typeString(typ.Key()) + "]" + p.typeString(typ.Elem())
	case *types.Chan:
		switch typ.Dir() {
		case types.SendOnly:
			return "chan<- " + p.typeString(typ.Elem())
		case types.RecvOnly:
			return "<-chan " + p.typeString(typ.Elem())
		default:
			return "chan " + p.typeString(typ.Elem())
		}
	case *types.Named:
		return p.namedType(typ.Obj(), typ.TypeArgs())
	case *types.Alias:
		return p.namedType(typ.Obj(), typ.TypeArgs())
	case *types.TypeParam:
		return typ.Obj().Name()
	case *types.Union:
		terms := make([]string, typ.Len())
		for i := range typ.Len() {
			term := typ.Term(i)
			prefix := ""
			if term.Tilde() {
				prefix = "~"
			}
			terms[i] = prefix + p.typeString(term.Type())
		}
		sort.Strings(terms)
		return strings.Join(terms, " | ")
	default:
		return types.TypeString(typ, p.qualifier)
	}
}

func (p apiPrinter) namedType(obj *types.TypeName, args *types.TypeList) string {
	name := obj.Name()
	if obj.Pkg() != nil && obj.Pkg() != p.pkg {
		name = obj.Pkg().Path() + "." + name
	}
	if args == nil || args.Len() == 0 {
		return name
	}
	typeArgs := make([]string, args.Len())
	for i := range args.Len() {
		typeArgs[i] = p.typeString(args.At(i))
	}
	return name + "[" + strings.Join(typeArgs, ", ") + "]"
}

func (p apiPrinter) structType(strct *types.Struct) string {
	fields := make([]string, 0, strct.NumFields()+1)
	hasUnexported := false
	for i := range strct.NumFields() {
		field := strct.Field(i)
		if !field.Exported() {
			hasUnexported = true
			continue
		}
		entry := ""
		if !field.Embedded() {
			entry = field.Name() + " "
		}
		entry += p.typeString(field.Type())
		if tag := strct.Tag(i); tag != "" {
			entry += " " + strconv.Quote(tag)
		}
		fields = append(fields, entry)
	}
	if hasUnexported {
		fields = append(fields, fmt.Sprintf("/* unexported fields; comparable=%t */", types.Comparable(strct)))
	}
	return "struct{" + strings.Join(fields, "; ") + "}"
}

func (p apiPrinter) interfaceType(iface *types.Interface) string {
	iface.Complete()
	parts := make([]string, 0, iface.NumExplicitMethods()+iface.NumEmbeddeds())
	for method := range iface.ExplicitMethods() {
		parts = append(parts, method.Name()+p.signature(method.Signature()))
	}
	for embedded := range iface.EmbeddedTypes() {
		parts = append(parts, p.typeString(embedded))
	}
	sort.Strings(parts)
	return "interface{" + strings.Join(parts, "; ") + "}"
}

func (p apiPrinter) signature(sig *types.Signature) string {
	return p.typeParameters(sig.TypeParams()) + p.tuple(sig.Params(), sig.Variadic()) + p.results(sig.Results())
}

func (p apiPrinter) tuple(tuple *types.Tuple, variadic bool) string {
	if tuple == nil || tuple.Len() == 0 {
		return "()"
	}
	parts := make([]string, tuple.Len())
	for i := range tuple.Len() {
		typ := tuple.At(i).Type()
		if variadic && i == tuple.Len()-1 {
			if slice, ok := typ.(*types.Slice); ok {
				parts[i] = "..." + p.typeString(slice.Elem())
				continue
			}
		}
		parts[i] = p.typeString(typ)
	}
	return "(" + strings.Join(parts, ", ") + ")"
}

func (p apiPrinter) results(results *types.Tuple) string {
	if results == nil || results.Len() == 0 {
		return ""
	}
	if results.Len() == 1 {
		return " " + p.typeString(results.At(0).Type())
	}
	return " " + p.tuple(results, false)
}

func (p apiPrinter) exportedMethods(obj *types.TypeName) []string {
	methods := make([]string, 0)
	valueMethods := make(map[string]struct{})
	receiver := p.receiverName(obj)

	appendMethodSet := func(methodSet *types.MethodSet, displayReceiver string, skip map[string]struct{}) {
		for selection := range methodSet.Methods() {
			method, ok := selection.Obj().(*types.Func)
			if !ok || !method.Exported() {
				continue
			}
			if _, exists := skip[method.Name()]; exists {
				continue
			}
			signature, ok := selection.Type().(*types.Signature)
			if !ok {
				continue
			}
			valueMethods[method.Name()] = struct{}{}
			methods = append(methods, "method: `func ("+displayReceiver+")."+method.Name()+p.signature(signature)+"`")
		}
	}

	appendMethodSet(types.NewMethodSet(obj.Type()), receiver, nil)
	appendMethodSet(types.NewMethodSet(types.NewPointer(obj.Type())), "*"+receiver, valueMethods)
	sort.Strings(methods)
	return methods
}

func (p apiPrinter) receiverName(obj *types.TypeName) string {
	name := obj.Name()
	var params *types.TypeParamList
	switch typ := obj.Type().(type) {
	case *types.Named:
		params = typ.TypeParams()
	case *types.Alias:
		params = typ.TypeParams()
	}
	if params == nil || params.Len() == 0 {
		return name
	}
	arguments := make([]string, params.Len())
	for i := range params.Len() {
		arguments[i] = params.At(i).Obj().Name()
	}
	return name + "[" + strings.Join(arguments, ", ") + "]"
}

func (p apiPrinter) qualifier(other *types.Package) string {
	if other == p.pkg {
		return ""
	}
	return other.Path()
}

func checkCompatibility(current []byte, baselinePath, allowPath, expectedPath, removalsPath string) error {
	baseline, err := os.ReadFile(baselinePath)
	if err != nil {
		return fmt.Errorf("read baseline: %w", err)
	}
	currentEntries, err := parseInventory(current)
	if err != nil {
		return fmt.Errorf("parse current inventory: %w", err)
	}
	baselineEntries, err := parseInventory(baseline)
	if err != nil {
		return fmt.Errorf("parse baseline: %w", err)
	}

	if (allowPath == "") != (expectedPath == "") {
		return fmt.Errorf("-allow-breaking and -expect-breaking must be supplied together")
	}

	allowed := newInventory()
	if allowPath != "" {
		allowData, readErr := os.ReadFile(allowPath)
		if readErr != nil {
			return fmt.Errorf("read allowlist: %w", readErr)
		}
		allowed, err = parseInventory(allowData)
		if err != nil {
			return fmt.Errorf("parse allowlist: %w", err)
		}
	}
	expected := newInventory()
	if expectedPath != "" {
		expectedData, readErr := os.ReadFile(expectedPath)
		if readErr != nil {
			return fmt.Errorf("read expected replacements: %w", readErr)
		}
		expected, err = parseInventory(expectedData)
		if err != nil {
			return fmt.Errorf("parse expected replacements: %w", err)
		}
	}
	removals := newInventory()
	if removalsPath != "" {
		removalsData, readErr := os.ReadFile(removalsPath)
		if readErr != nil {
			return fmt.Errorf("read approved removals: %w", readErr)
		}
		removals, err = parseInventory(removalsData)
		if err != nil {
			return fmt.Errorf("parse approved removals: %w", err)
		}
	}
	var invalidAllowlist []string
	for slot, before := range allowed.slots {
		after, paired := expected.slots[slot]
		if !paired {
			invalidAllowlist = append(invalidAllowlist, "missing expected replacement for "+slot+": "+before.key)
		}
		if _, ok := baselineEntries.entries[before.key]; !ok {
			invalidAllowlist = append(invalidAllowlist, "not present in baseline: "+before.key)
			continue
		}
		if _, ok := currentEntries.entries[before.key]; ok {
			invalidAllowlist = append(invalidAllowlist, "no longer needed: "+before.key)
		}
		if paired {
			if _, ok := currentEntries.entries[after.key]; !ok {
				invalidAllowlist = append(invalidAllowlist, "approved replacement is not current: "+after.key)
			}
			if _, ok := baselineEntries.entries[after.key]; ok {
				invalidAllowlist = append(invalidAllowlist, "replacement already exists in baseline: "+after.key)
			}
		}
	}
	for slot, after := range expected.slots {
		if _, paired := allowed.slots[slot]; !paired {
			invalidAllowlist = append(invalidAllowlist, "expected replacement has no matching old entry for "+slot+": "+after.key)
		}
	}
	for slot, removal := range removals.slots {
		if _, ok := baselineEntries.entries[removal.key]; !ok {
			invalidAllowlist = append(invalidAllowlist, "approved removal is not present in baseline: "+removal.key)
			continue
		}
		if _, paired := allowed.slots[slot]; paired {
			invalidAllowlist = append(invalidAllowlist, "API slot is approved as both replacement and removal: "+slot)
		}
		if _, ok := currentEntries.entries[removal.key]; ok {
			invalidAllowlist = append(invalidAllowlist, "approved removal is still current: "+removal.key)
			continue
		}
		if after, ok := currentEntries.slots[slot]; ok {
			invalidAllowlist = append(invalidAllowlist, "approved removal has a current replacement; use the paired replacement files: "+after.key)
		}
	}
	if len(invalidAllowlist) > 0 {
		sort.Strings(invalidAllowlist)
		return fmt.Errorf("invalid compatibility allowlist:\n  %s", strings.Join(invalidAllowlist, "\n  "))
	}

	var incompatible []string
	for entry := range baselineEntries.entries {
		if _, ok := currentEntries.entries[entry]; ok {
			continue
		}
		if _, ok := allowed.entries[entry]; ok {
			continue
		}
		if _, ok := removals.entries[entry]; ok {
			continue
		}
		incompatible = append(incompatible, entry)
	}
	if len(incompatible) > 0 {
		sort.Strings(incompatible)
		return fmt.Errorf("unreviewed exported API removals or changes:\n  %s", strings.Join(incompatible, "\n  "))
	}
	return nil
}

type inventoryEntry struct {
	key  string
	slot string
}

type inventory struct {
	entries map[string]inventoryEntry
	slots   map[string]inventoryEntry
}

func newInventory() *inventory {
	return &inventory{
		entries: make(map[string]inventoryEntry),
		slots:   make(map[string]inventoryEntry),
	}
}

func parseInventory(data []byte) (*inventory, error) {
	inventory := newInventory()
	currentPackage := ""
	for line := range strings.Lines(string(data)) {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "## `") && strings.HasSuffix(line, "`") {
			currentPackage = strings.TrimSuffix(strings.TrimPrefix(line, "## `"), "`")
			continue
		}
		if !strings.HasPrefix(line, "- ") {
			continue
		}
		if currentPackage == "" {
			return nil, fmt.Errorf("entry appears before a package heading: %s", line)
		}
		key := currentPackage + "\n" + line
		if _, duplicate := inventory.entries[key]; duplicate {
			return nil, fmt.Errorf("duplicate inventory entry: %s", key)
		}
		slot, err := inventorySlot(currentPackage, line)
		if err != nil {
			return nil, err
		}
		if previous, duplicate := inventory.slots[slot]; duplicate {
			return nil, fmt.Errorf("multiple entries occupy API slot %s: %s and %s", slot, previous.key, key)
		}
		entry := inventoryEntry{key: key, slot: slot}
		inventory.entries[key] = entry
		inventory.slots[slot] = entry
	}
	return inventory, nil
}

func inventorySlot(pkg, line string) (string, error) {
	payload := strings.TrimPrefix(line, "- ")
	separator := strings.Index(payload, ": `")
	if separator < 1 || !strings.HasSuffix(payload, "`") {
		return "", fmt.Errorf("invalid inventory entry in package %s: %s", pkg, line)
	}
	kind := payload[:separator]
	declaration := strings.TrimSuffix(payload[separator+3:], "`")
	var identity string
	switch kind {
	case "const", "var", "type":
		prefix := kind + " "
		if !strings.HasPrefix(declaration, prefix) {
			return "", fmt.Errorf("invalid %s declaration in package %s: %s", kind, pkg, line)
		}
		identity = leadingIdentifier(strings.TrimPrefix(declaration, prefix))
	case "func":
		if !strings.HasPrefix(declaration, "func ") {
			return "", fmt.Errorf("invalid function declaration in package %s: %s", pkg, line)
		}
		identity = leadingIdentifier(strings.TrimPrefix(declaration, "func "))
	case "method":
		if !strings.HasPrefix(declaration, "func (") {
			return "", fmt.Errorf("invalid method declaration in package %s: %s", pkg, line)
		}
		receiverEnd := strings.Index(declaration, ").")
		if receiverEnd < 0 {
			return "", fmt.Errorf("invalid method receiver in package %s: %s", pkg, line)
		}
		receiver := strings.TrimPrefix(declaration[len("func ("):receiverEnd], "*")
		if typeArguments := strings.IndexByte(receiver, '['); typeArguments >= 0 {
			receiver = receiver[:typeArguments]
		}
		method := leadingIdentifier(declaration[receiverEnd+2:])
		if receiver == "" || method == "" {
			return "", fmt.Errorf("invalid method identity in package %s: %s", pkg, line)
		}
		identity = receiver + "." + method
	default:
		return "", fmt.Errorf("unknown inventory entry kind %q in package %s", kind, pkg)
	}
	if identity == "" {
		return "", fmt.Errorf("missing API identity in package %s: %s", pkg, line)
	}
	return pkg + "\n" + kind + ":" + identity, nil
}

func leadingIdentifier(value string) string {
	for i, r := range value {
		if i == 0 {
			if valid := r == '_' || unicode.IsLetter(r); !valid {
				return ""
			}
			continue
		}
		if valid := r == '_' || unicode.IsLetter(r) || unicode.IsDigit(r); !valid {
			return value[:i]
		}
	}
	return value
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "apiinventory: "+format+"\n", args...)
	os.Exit(1)
}
