// Command apiinventory generates the reviewed Genesis v1 exported API surface.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/token"
	"go/types"
	"os"
	"sort"
	"strings"

	"golang.org/x/tools/go/packages"
)

const header = `# Genesis v1 exported API inventory

This file is generated by ` + "`go run ./internal/cmd/apiinventory`" + `. It inventories exported constants, variables, types, functions, and methods that form the v1 review surface. Packages under ` + "`examples`" + ` and ` + "`internal`" + ` are excluded; ` + "`testkit`" + ` is included because it is an importable module package.

`

func main() {
	writePath := flag.String("write", "", "write the generated inventory to this path")
	checkPath := flag.String("check", "", "fail if this path differs from the generated inventory")
	flag.Parse()
	if *writePath != "" && *checkPath != "" {
		fatalf("-write and -check are mutually exclusive")
	}

	generated, err := generate()
	if err != nil {
		fatalf("generate inventory: %v", err)
	}
	switch {
	case *writePath != "":
		if err := os.WriteFile(*writePath, generated, 0o644); err != nil {
			fatalf("write inventory: %v", err)
		}
	case *checkPath != "":
		current, err := os.ReadFile(*checkPath)
		if err != nil {
			fatalf("read inventory: %v", err)
		}
		if !bytes.Equal(current, generated) {
			fatalf("%s is stale; run make api-inventory", *checkPath)
		}
	default:
		_, _ = os.Stdout.Write(generated)
	}
}

func generate() ([]byte, error) {
	cfg := &packages.Config{Mode: packages.NeedName | packages.NeedTypes | packages.NeedModule}
	loaded, err := packages.Load(cfg, "./...")
	if err != nil {
		return nil, err
	}
	if packages.PrintErrors(loaded) > 0 {
		return nil, fmt.Errorf("package loading failed")
	}

	pkgs := make([]*packages.Package, 0, len(loaded))
	for _, pkg := range loaded {
		if pkg.Module == nil || pkg.PkgPath == "" || pkg.Name == "main" {
			continue
		}
		rel := strings.TrimPrefix(pkg.PkgPath, pkg.Module.Path)
		if strings.HasPrefix(rel, "/examples/") || rel == "/examples" || strings.HasPrefix(rel, "/internal/") || rel == "/internal" {
			continue
		}
		pkgs = append(pkgs, pkg)
	}
	sort.Slice(pkgs, func(i, j int) bool { return pkgs[i].PkgPath < pkgs[j].PkgPath })

	var out bytes.Buffer
	out.WriteString(header)
	for _, pkg := range pkgs {
		rel := strings.TrimPrefix(pkg.PkgPath, pkg.Module.Path+"/")
		fmt.Fprintf(&out, "## `%s`\n\n", rel)
		for _, entry := range packageEntries(pkg.Types) {
			fmt.Fprintf(&out, "- %s\n", entry)
		}
		out.WriteByte('\n')
	}
	return append(bytes.TrimRight(out.Bytes(), "\n"), '\n'), nil
}

func packageEntries(pkg *types.Package) []string {
	qualifier := func(other *types.Package) string {
		if other == pkg {
			return ""
		}
		return other.Name()
	}

	entries := make([]string, 0)
	scope := pkg.Scope()
	for _, name := range scope.Names() {
		if !token.IsExported(name) {
			continue
		}
		obj := scope.Lookup(name)
		switch value := obj.(type) {
		case *types.Const:
			entries = append(entries, "const: `const "+value.Name()+"`")
		case *types.Var:
			entries = append(entries, "var: `var "+value.Name()+"`")
		case *types.Func:
			entries = append(entries, "func: `"+types.ObjectString(value, qualifier)+"`")
		case *types.TypeName:
			entries = append(entries, "type: `"+types.ObjectString(value, qualifier)+"`")
			if named, ok := types.Unalias(value.Type()).(*types.Named); ok {
				entries = append(entries, exportedMethods(named, qualifier)...)
			}
		}
	}
	sort.Strings(entries)
	return entries
}

func exportedMethods(named *types.Named, qualifier types.Qualifier) []string {
	methods := make([]string, 0)
	for method := range named.Methods() {
		if method.Exported() {
			methods = append(methods, "method: `"+types.ObjectString(method, qualifier)+"`")
		}
	}
	return methods
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "apiinventory: "+format+"\n", args...)
	os.Exit(1)
}
