// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v7.34.1
// source: examples/observability/internal/proto/order.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderService_CreateOrder_FullMethodName = "/proto.OrderService/CreateOrder"
)

// OrderServiceClient is the client API for OrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderServiceClient interface {
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
}

type orderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderServiceClient(cc grpc.ClientConnInterface) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOrderResponse)
	err := c.cc.Invoke(ctx, OrderService_CreateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServiceServer is the server API for OrderService service.
// All implementations must embed UnimplementedOrderServiceServer
// for forward compatibility.
type OrderServiceServer interface {
	CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error)
	mustEmbedUnimplementedOrderServiceServer()
}

// UnimplementedOrderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderServiceServer struct{}

func (UnimplementedOrderServiceServer) CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedOrderServiceServer) mustEmbedUnimplementedOrderServiceServer() {}
func (UnimplementedOrderServiceServer) testEmbeddedByValue()                      {}

// UnsafeOrderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderServiceServer will
// result in compilation errors.
type UnsafeOrderServiceServer interface {
	mustEmbedUnimplementedOrderServiceServer()
}

func RegisterOrderServiceServer(s grpc.ServiceRegistrar, srv OrderServiceServer) {
	// If the following call panics, it indicates UnimplementedOrderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderService_ServiceDesc, srv)
}

func _OrderService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_CreateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderService_ServiceDesc is the grpc.ServiceDesc for OrderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _OrderService_CreateOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "examples/observability/internal/proto/order.proto",
}

const (
	GatewayCallbackService_PushResult_FullMethodName = "/proto.GatewayCallbackService/PushResult"
)

// GatewayCallbackServiceClient is the client API for GatewayCallbackService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayCallbackServiceClient interface {
	PushResult(ctx context.Context, in *PushResultRequest, opts ...grpc.CallOption) (*PushResultResponse, error)
}

type gatewayCallbackServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayCallbackServiceClient(cc grpc.ClientConnInterface) GatewayCallbackServiceClient {
	return &gatewayCallbackServiceClient{cc}
}

func (c *gatewayCallbackServiceClient) PushResult(ctx context.Context, in *PushResultRequest, opts ...grpc.CallOption) (*PushResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushResultResponse)
	err := c.cc.Invoke(ctx, GatewayCallbackService_PushResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayCallbackServiceServer is the server API for GatewayCallbackService service.
// All implementations must embed UnimplementedGatewayCallbackServiceServer
// for forward compatibility.
type GatewayCallbackServiceServer interface {
	PushResult(context.Context, *PushResultRequest) (*PushResultResponse, error)
	mustEmbedUnimplementedGatewayCallbackServiceServer()
}

// UnimplementedGatewayCallbackServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayCallbackServiceServer struct{}

func (UnimplementedGatewayCallbackServiceServer) PushResult(context.Context, *PushResultRequest) (*PushResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PushResult not implemented")
}
func (UnimplementedGatewayCallbackServiceServer) mustEmbedUnimplementedGatewayCallbackServiceServer() {
}
func (UnimplementedGatewayCallbackServiceServer) testEmbeddedByValue() {}

// UnsafeGatewayCallbackServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayCallbackServiceServer will
// result in compilation errors.
type UnsafeGatewayCallbackServiceServer interface {
	mustEmbedUnimplementedGatewayCallbackServiceServer()
}

func RegisterGatewayCallbackServiceServer(s grpc.ServiceRegistrar, srv GatewayCallbackServiceServer) {
	// If the following call panics, it indicates UnimplementedGatewayCallbackServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayCallbackService_ServiceDesc, srv)
}

func _GatewayCallbackService_PushResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayCallbackServiceServer).PushResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayCallbackService_PushResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayCallbackServiceServer).PushResult(ctx, req.(*PushResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GatewayCallbackService_ServiceDesc is the grpc.ServiceDesc for GatewayCallbackService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayCallbackService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.GatewayCallbackService",
	HandlerType: (*GatewayCallbackServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushResult",
			Handler:    _GatewayCallbackService_PushResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "examples/observability/internal/proto/order.proto",
}
