// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: examples/observability/internal/proto/order.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_examples_observability_internal_proto_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_observability_internal_proto_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_examples_observability_internal_proto_order_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateOrderRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_examples_observability_internal_proto_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_observability_internal_proto_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_examples_observability_internal_proto_order_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrderResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateOrderResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type OrderResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderResult) Reset() {
	*x = OrderResult{}
	mi := &file_examples_observability_internal_proto_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderResult) ProtoMessage() {}

func (x *OrderResult) ProtoReflect() protoreflect.Message {
	mi := &file_examples_observability_internal_proto_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderResult.ProtoReflect.Descriptor instead.
func (*OrderResult) Descriptor() ([]byte, []int) {
	return file_examples_observability_internal_proto_order_proto_rawDescGZIP(), []int{2}
}

func (x *OrderResult) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type PushResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *OrderResult           `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushResultRequest) Reset() {
	*x = PushResultRequest{}
	mi := &file_examples_observability_internal_proto_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushResultRequest) ProtoMessage() {}

func (x *PushResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_observability_internal_proto_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushResultRequest.ProtoReflect.Descriptor instead.
func (*PushResultRequest) Descriptor() ([]byte, []int) {
	return file_examples_observability_internal_proto_order_proto_rawDescGZIP(), []int{3}
}

func (x *PushResultRequest) GetResult() *OrderResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type PushResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushResultResponse) Reset() {
	*x = PushResultResponse{}
	mi := &file_examples_observability_internal_proto_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushResultResponse) ProtoMessage() {}

func (x *PushResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_observability_internal_proto_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushResultResponse.ProtoReflect.Descriptor instead.
func (*PushResultResponse) Descriptor() ([]byte, []int) {
	return file_examples_observability_internal_proto_order_proto_rawDescGZIP(), []int{4}
}

func (x *PushResultResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_examples_observability_internal_proto_order_proto protoreflect.FileDescriptor

const file_examples_observability_internal_proto_order_proto_rawDesc = "" +
	"\n" +
	"1examples/observability/internal/proto/order.proto\x12\x05proto\"L\n" +
	"\x12CreateOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\"H\n" +
	"\x13CreateOrderResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"@\n" +
	"\vOrderResult\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"?\n" +
	"\x11PushResultRequest\x12*\n" +
	"\x06result\x18\x01 \x01(\v2\x12.proto.OrderResultR\x06result\"$\n" +
	"\x12PushResultResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2T\n" +
	"\fOrderService\x12D\n" +
	"\vCreateOrder\x12\x19.proto.CreateOrderRequest\x1a\x1a.proto.CreateOrderResponse2[\n" +
	"\x16GatewayCallbackService\x12A\n" +
	"\n" +
	"PushResult\x12\x18.proto.PushResultRequest\x1a\x19.proto.PushResultResponseBHZFgithub.com/ceyewan/genesis/examples/observability/internal/proto;protob\x06proto3"

var (
	file_examples_observability_internal_proto_order_proto_rawDescOnce sync.Once
	file_examples_observability_internal_proto_order_proto_rawDescData []byte
)

func file_examples_observability_internal_proto_order_proto_rawDescGZIP() []byte {
	file_examples_observability_internal_proto_order_proto_rawDescOnce.Do(func() {
		file_examples_observability_internal_proto_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_observability_internal_proto_order_proto_rawDesc), len(file_examples_observability_internal_proto_order_proto_rawDesc)))
	})
	return file_examples_observability_internal_proto_order_proto_rawDescData
}

var file_examples_observability_internal_proto_order_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_examples_observability_internal_proto_order_proto_goTypes = []any{
	(*CreateOrderRequest)(nil),  // 0: proto.CreateOrderRequest
	(*CreateOrderResponse)(nil), // 1: proto.CreateOrderResponse
	(*OrderResult)(nil),         // 2: proto.OrderResult
	(*PushResultRequest)(nil),   // 3: proto.PushResultRequest
	(*PushResultResponse)(nil),  // 4: proto.PushResultResponse
}
var file_examples_observability_internal_proto_order_proto_depIdxs = []int32{
	2, // 0: proto.PushResultRequest.result:type_name -> proto.OrderResult
	0, // 1: proto.OrderService.CreateOrder:input_type -> proto.CreateOrderRequest
	3, // 2: proto.GatewayCallbackService.PushResult:input_type -> proto.PushResultRequest
	1, // 3: proto.OrderService.CreateOrder:output_type -> proto.CreateOrderResponse
	4, // 4: proto.GatewayCallbackService.PushResult:output_type -> proto.PushResultResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_examples_observability_internal_proto_order_proto_init() }
func file_examples_observability_internal_proto_order_proto_init() {
	if File_examples_observability_internal_proto_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_observability_internal_proto_order_proto_rawDesc), len(file_examples_observability_internal_proto_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_examples_observability_internal_proto_order_proto_goTypes,
		DependencyIndexes: file_examples_observability_internal_proto_order_proto_depIdxs,
		MessageInfos:      file_examples_observability_internal_proto_order_proto_msgTypes,
	}.Build()
	File_examples_observability_internal_proto_order_proto = out.File
	file_examples_observability_internal_proto_order_proto_goTypes = nil
	file_examples_observability_internal_proto_order_proto_depIdxs = nil
}
