// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: examples/breaker/proto/test.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CallRequest 调用请求
type CallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	ShouldFail    bool                   `protobuf:"varint,2,opt,name=should_fail,json=shouldFail,proto3" json:"should_fail,omitempty"` // 是否应该失败（用于模拟故障）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallRequest) Reset() {
	*x = CallRequest{}
	mi := &file_examples_breaker_proto_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallRequest) ProtoMessage() {}

func (x *CallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_breaker_proto_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallRequest.ProtoReflect.Descriptor instead.
func (*CallRequest) Descriptor() ([]byte, []int) {
	return file_examples_breaker_proto_test_proto_rawDescGZIP(), []int{0}
}

func (x *CallRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CallRequest) GetShouldFail() bool {
	if x != nil {
		return x.ShouldFail
	}
	return false
}

// CallResponse 调用响应
type CallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallResponse) Reset() {
	*x = CallResponse{}
	mi := &file_examples_breaker_proto_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallResponse) ProtoMessage() {}

func (x *CallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_breaker_proto_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallResponse.ProtoReflect.Descriptor instead.
func (*CallResponse) Descriptor() ([]byte, []int) {
	return file_examples_breaker_proto_test_proto_rawDescGZIP(), []int{1}
}

func (x *CallResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CallResponse) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *CallResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// StreamRequest 流式请求
type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_examples_breaker_proto_test_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_breaker_proto_test_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_examples_breaker_proto_test_proto_rawDescGZIP(), []int{2}
}

func (x *StreamRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// StreamResponse 流式响应
type StreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamResponse) Reset() {
	*x = StreamResponse{}
	mi := &file_examples_breaker_proto_test_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_breaker_proto_test_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse.ProtoReflect.Descriptor instead.
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return file_examples_breaker_proto_test_proto_rawDescGZIP(), []int{3}
}

func (x *StreamResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StreamResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_examples_breaker_proto_test_proto protoreflect.FileDescriptor

const file_examples_breaker_proto_test_proto_rawDesc = "" +
	"\n" +
	"!examples/breaker/proto/test.proto\x12\x04test\"H\n" +
	"\vCallRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1f\n" +
	"\vshould_fail\x18\x02 \x01(\bR\n" +
	"shouldFail\"c\n" +
	"\fCallResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\")\n" +
	"\rStreamRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"H\n" +
	"\x0eStreamResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp2y\n" +
	"\vTestService\x12-\n" +
	"\x04Call\x12\x11.test.CallRequest\x1a\x12.test.CallResponse\x12;\n" +
	"\n" +
	"StreamCall\x12\x13.test.StreamRequest\x1a\x14.test.StreamResponse(\x010\x01B9Z7github.com/ceyewan/genesis/examples/breaker/proto;protob\x06proto3"

var (
	file_examples_breaker_proto_test_proto_rawDescOnce sync.Once
	file_examples_breaker_proto_test_proto_rawDescData []byte
)

func file_examples_breaker_proto_test_proto_rawDescGZIP() []byte {
	file_examples_breaker_proto_test_proto_rawDescOnce.Do(func() {
		file_examples_breaker_proto_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_breaker_proto_test_proto_rawDesc), len(file_examples_breaker_proto_test_proto_rawDesc)))
	})
	return file_examples_breaker_proto_test_proto_rawDescData
}

var file_examples_breaker_proto_test_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_examples_breaker_proto_test_proto_goTypes = []any{
	(*CallRequest)(nil),    // 0: test.CallRequest
	(*CallResponse)(nil),   // 1: test.CallResponse
	(*StreamRequest)(nil),  // 2: test.StreamRequest
	(*StreamResponse)(nil), // 3: test.StreamResponse
}
var file_examples_breaker_proto_test_proto_depIdxs = []int32{
	0, // 0: test.TestService.Call:input_type -> test.CallRequest
	2, // 1: test.TestService.StreamCall:input_type -> test.StreamRequest
	1, // 2: test.TestService.Call:output_type -> test.CallResponse
	3, // 3: test.TestService.StreamCall:output_type -> test.StreamResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_examples_breaker_proto_test_proto_init() }
func file_examples_breaker_proto_test_proto_init() {
	if File_examples_breaker_proto_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_breaker_proto_test_proto_rawDesc), len(file_examples_breaker_proto_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_examples_breaker_proto_test_proto_goTypes,
		DependencyIndexes: file_examples_breaker_proto_test_proto_depIdxs,
		MessageInfos:      file_examples_breaker_proto_test_proto_msgTypes,
	}.Build()
	File_examples_breaker_proto_test_proto = out.File
	file_examples_breaker_proto_test_proto_goTypes = nil
	file_examples_breaker_proto_test_proto_depIdxs = nil
}
