// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: examples/proto/demo/v1/order.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateOrderRequest 创建订单请求
type CreateOrderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 幂等性键（idem 组件使用）
	IdempotencyKey string `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// 订单基本信息
	OrderId     string  `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CustomerId  string  `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Amount      float64 `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Description string  `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	// 测试控制字段（breaker 组件使用）
	ShouldFail    bool `protobuf:"varint,10,opt,name=should_fail,json=shouldFail,proto3" json:"should_fail,omitempty"` // 是否应该失败（用于模拟故障）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_examples_proto_demo_v1_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_demo_v1_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_examples_proto_demo_v1_order_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *CreateOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateOrderRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CreateOrderRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateOrderRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateOrderRequest) GetShouldFail() bool {
	if x != nil {
		return x.ShouldFail
	}
	return false
}

// CreateOrderResponse 创建订单响应
type CreateOrderResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	OrderId   string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status    string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Amount    float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Timestamp int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// 服务信息（registry 组件使用）
	ServerId      string `protobuf:"bytes,10,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`       // 服务器唯一标识
	ServerAddr    string `protobuf:"bytes,11,opt,name=server_addr,json=serverAddr,proto3" json:"server_addr,omitempty"` // 服务器地址
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_examples_proto_demo_v1_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_demo_v1_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_examples_proto_demo_v1_order_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrderResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateOrderResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateOrderResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateOrderResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *CreateOrderResponse) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *CreateOrderResponse) GetServerAddr() string {
	if x != nil {
		return x.ServerAddr
	}
	return ""
}

// StreamOrdersRequest 流式请求
type StreamOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamOrdersRequest) Reset() {
	*x = StreamOrdersRequest{}
	mi := &file_examples_proto_demo_v1_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOrdersRequest) ProtoMessage() {}

func (x *StreamOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_demo_v1_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamOrdersRequest.ProtoReflect.Descriptor instead.
func (*StreamOrdersRequest) Descriptor() ([]byte, []int) {
	return file_examples_proto_demo_v1_order_proto_rawDescGZIP(), []int{2}
}

func (x *StreamOrdersRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// StreamOrdersResponse 流式响应
type StreamOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ServerId      string                 `protobuf:"bytes,3,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamOrdersResponse) Reset() {
	*x = StreamOrdersResponse{}
	mi := &file_examples_proto_demo_v1_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOrdersResponse) ProtoMessage() {}

func (x *StreamOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_demo_v1_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamOrdersResponse.ProtoReflect.Descriptor instead.
func (*StreamOrdersResponse) Descriptor() ([]byte, []int) {
	return file_examples_proto_demo_v1_order_proto_rawDescGZIP(), []int{3}
}

func (x *StreamOrdersResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StreamOrdersResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *StreamOrdersResponse) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

var File_examples_proto_demo_v1_order_proto protoreflect.FileDescriptor

const file_examples_proto_demo_v1_order_proto_rawDesc = "" +
	"\n" +
	"\"examples/proto/demo/v1/order.proto\x12\ademo.v1\"\xd4\x01\n" +
	"\x12CreateOrderRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x1f\n" +
	"\vcustomer_id\x18\x03 \x01(\tR\n" +
	"customerId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1f\n" +
	"\vshould_fail\x18\n" +
	" \x01(\bR\n" +
	"shouldFail\"\xbc\x01\n" +
	"\x13CreateOrderResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\tserver_id\x18\n" +
	" \x01(\tR\bserverId\x12\x1f\n" +
	"\vserver_addr\x18\v \x01(\tR\n" +
	"serverAddr\"/\n" +
	"\x13StreamOrdersRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"k\n" +
	"\x14StreamOrdersResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\tserver_id\x18\x03 \x01(\tR\bserverId2\xa9\x01\n" +
	"\fOrderService\x12H\n" +
	"\vCreateOrder\x12\x1b.demo.v1.CreateOrderRequest\x1a\x1c.demo.v1.CreateOrderResponse\x12O\n" +
	"\fStreamOrders\x12\x1c.demo.v1.StreamOrdersRequest\x1a\x1d.demo.v1.StreamOrdersResponse(\x010\x01B6Z4github.com/ceyewan/genesis/examples/proto/demo/v1;pbb\x06proto3"

var (
	file_examples_proto_demo_v1_order_proto_rawDescOnce sync.Once
	file_examples_proto_demo_v1_order_proto_rawDescData []byte
)

func file_examples_proto_demo_v1_order_proto_rawDescGZIP() []byte {
	file_examples_proto_demo_v1_order_proto_rawDescOnce.Do(func() {
		file_examples_proto_demo_v1_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_proto_demo_v1_order_proto_rawDesc), len(file_examples_proto_demo_v1_order_proto_rawDesc)))
	})
	return file_examples_proto_demo_v1_order_proto_rawDescData
}

var file_examples_proto_demo_v1_order_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_examples_proto_demo_v1_order_proto_goTypes = []any{
	(*CreateOrderRequest)(nil),   // 0: demo.v1.CreateOrderRequest
	(*CreateOrderResponse)(nil),  // 1: demo.v1.CreateOrderResponse
	(*StreamOrdersRequest)(nil),  // 2: demo.v1.StreamOrdersRequest
	(*StreamOrdersResponse)(nil), // 3: demo.v1.StreamOrdersResponse
}
var file_examples_proto_demo_v1_order_proto_depIdxs = []int32{
	0, // 0: demo.v1.OrderService.CreateOrder:input_type -> demo.v1.CreateOrderRequest
	2, // 1: demo.v1.OrderService.StreamOrders:input_type -> demo.v1.StreamOrdersRequest
	1, // 2: demo.v1.OrderService.CreateOrder:output_type -> demo.v1.CreateOrderResponse
	3, // 3: demo.v1.OrderService.StreamOrders:output_type -> demo.v1.StreamOrdersResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_examples_proto_demo_v1_order_proto_init() }
func file_examples_proto_demo_v1_order_proto_init() {
	if File_examples_proto_demo_v1_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_proto_demo_v1_order_proto_rawDesc), len(file_examples_proto_demo_v1_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_examples_proto_demo_v1_order_proto_goTypes,
		DependencyIndexes: file_examples_proto_demo_v1_order_proto_depIdxs,
		MessageInfos:      file_examples_proto_demo_v1_order_proto_msgTypes,
	}.Build()
	File_examples_proto_demo_v1_order_proto = out.File
	file_examples_proto_demo_v1_order_proto_goTypes = nil
	file_examples_proto_demo_v1_order_proto_depIdxs = nil
}
